HomeCinema/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MapperProfiles.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using HomeCinema.Services.Helpers;
using AutoMapper;
using HomeCinema.Services.Dto;
using HomeCinema.Services.Services;
using HomeCinema.Services.Interfaces;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace HomeCinema.Controllers
{
	public class FilmController : Controller
	{
		IMapper _mapper;
		private IServiceWithInclude<FilmDTO> _filmService;
		private readonly IHostingEnvironment _hostingEnv;

		public FilmController(IMapper mapper, IServiceWithInclude<FilmDTO> filmService, IHostingEnvironment environment)
		{
			_mapper = mapper;
			_hostingEnv = environment;
			_filmService = filmService;
		}

		[HttpPost]
		public IActionResult Add(IFormFile file, FilmForAddOrEditViewModel film)
		{
			var filmDTO = GetCollectionOfGenresAndActorsFromRequest.GetFilmDTOFromRequest(_mapper.Map<FilmDTO>(film), film.Actors, film.Genres);

			if (file != null)
			{
				filmDTO.Image = SaveFilmPoster(file).Result;
			}

			filmDTO.UserId = Guid.Parse(User.GetUserId());
			int FilmId = _filmService.Create(filmDTO).Id;

			return Ok(FilmId);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View("~/Views/Film/Add.cshtml");
		}

		[HttpPost]
		public async Task<IActionResult> Edit(IFormFile file, FilmForAddOrEditViewModel film)
		{
			string prevName = film.PreviousName.Replace("\r\n", "");
			var filmDTO = _mapper.Map<FilmDTO>(film);
			filmDTO.Id = _filmService.Get(prevName).Id;

			if (file != null)
			{
				filmDTO.Image = await SaveFilmPoster(file);
			}

			_filmService.Edit(filmDTO);

			return Ok();
		}


		private async Task<ImageDTO> SaveFilmPoster(IFormFile file)
		{
			string filePath = "";
			var a = _hostingEnv.WebRootPath;
			var fileName = Path.GetFileName(file.FileName);

			filePath = Path.Combine(_hostingEnv.WebRootPath, "images\\FilmsLogos", fileName);

			using (var fileSteam = new FileStream(filePath, FileMode.Create))
			{
				await file.CopyToAsync(fileSteam);
			}

			return new ImageDTO
			{
				ImageLink = fileName
			};

		}
	}
}

HomeCinema/Views/Film/Add.cshtml
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="edit-film" asp-action="Add" asp-controller="Film"
      enctype="multipart/form-data">

    <div class="wrap-container zerogrid">
        <button class="editButton" id="save-btn" type="submit">Сохранить</button>

        <div id="main-content" class="col-2-3">
            <div class="wrap-content">
                <article>
                    <div class="art-header">
                        <div class="col-1-3 image-film">
                            <input type="text" name="filmName" value="" class="edit-name" />
                            <div class="wrap-col film-logo">
                                <img src="~/images/FilmsLogos/No Country for Old Men.jpg" id="film-poster" style="width: 300px;height: 364px;opacity:0.3" />
                                <input type="file" name="imagePath" accept="image/x-png,image/gif,image/jpeg" id="select-image" />
                                <h4 class="edit-image-text">Кликните для изменения</h4>
                            </div>
                        </div>
                        <div class="col-2-3">


                            @Html.Partial("/Views/_Partial/ModalInput.cshtml")

                            <ul>

                                <li>
                                    <p id="genre-list">
                                        Жанры:




                                        <img src="~/images/plus.svg" class="plus-genre" alt="Plus Icon" onclick="changeFilmInfo('genre','Жанр',false,false)" />
                                    </p>
                                </li>

                                <li><p>Продюсер: <a href="#" class="produccer-text" name="produccer" onclick="changeFilmInfo('produccer','Продюссера',true,false)">Продюссер</a></p></li>
                                <li>
                                    <p id="actor-list">

                                        В главных ролях:


                                        <img src="~/images/plus.svg" class="plus-actor" alt="Plus Icon" onclick="changeFilmInfo('actor','Актера',false,false)" />
                                    </p>
                                </li>

                                <li><p>Дата Релиза: <a href="#" class="yearRelease-text" name="year" onclick="changeFilmInfo('yearRelease','Год релиза',true,true)">000</a></p></li>
                            </ul>
                        </div>
                    </div>
                    <div class="clear"></div>
            </div>
            <div class="art-content">
                <textarea>

                        </textarea>
                <div class="clear"></div>
            </div>
            </article>
          
        </div>
    </div>
    
    </div>
</form>

<script type="text/javascript">
     document.addEventListener("DOMContentLoaded", () => {
         addMode();

  });
    
</script>

HomeCinema/Views/Film/Single.cshtml
@using MapperProfiles.Models
@using HomeCinema.Services.Helpers

@model FilmViewModel
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form id="edit-film" asp-action="Edit" asp-controller="Film"
          enctype="multipart/form-data">

        <div class="wrap-container zerogrid">

            @if (User.Identity.IsAuthenticated)
            {
                if (User.GetUserId().Contains(Model.UserId.ToString()))
                {
                    <button class="editButton" id="edit-btn" type="button">Редактировать</button>
                    <button class="editButton" style="display:none" id="cancel-btn" type="button">Отмена</button>
                    <button class="editButton" style="display:none" id="save-btn" type="submit">Сохранить</button>
                }
            }

            <div id="main-content" class="col-2-3">
                <div class="wrap-content">
                    <article>
                        <div class="art-header">
                            <div class="col-1-3 image-film">
                                <h3 style="margin:7px;" id="film-name">@Model?.Name</h3>
                                <div class="wrap-col film-logo">
                                    <img src="~/images/FilmsLogos/@Model.Image?.ImageLink" id="film-poster" style="width: 300px;height: 364px;" />
                                    <input type="file" name="imagePath" accept="image/x-png,image/gif,image/jpeg" id="select-image" />
                                </div>
                            </div>
                            <div class="col-2-3">

                                <div class="wrap-col">

                                    @Html.Partial("/Views/_Partial/ModalInput.cshtml")

                                    <ul>

                                        <li>
                                            <p id="genre-list">
                                                Жанры:

                                                @foreach (var genre in Model?.Genres)
                                                {
                                                    <a href="#" class="genre-text">@genre.Name </a>
                                                }


                                                <img src="~/images/plus.svg" class="plus-genre" alt="Plus Icon" onclick="changeFilmInfo('genre','Жанр',false,false)" style="display:none" />
                                            </p>
                                        </li>

                                        <li><p>Продюсер: <a href="#" class="produccer-text" name="produccer" onclick="changeFilmInfo('produccer','Продюссера',true,false)">@Model.Producer</a></p></li>
                                        <li>
                                            <p id="actor-list">

                                                В главных ролях:

                                                @foreach (var actor in Model.Actors)
                                                {
                                                    <a href="#" class="actor-text">@actor.Name </a>
                                                }
                                                <img src="~/images/plus.svg" class="plus-actor" alt="Plus Icon" onclick="changeFilmInfo('actor','Актера',false,false)" style="display:none" />
                                            </p>
                                        </li>

                                        <li><p>Дата Релиза: <a href="#" class="yearRelease-text" name="year" onclick="changeFilmInfo('yearRelease','Год релиза',true,true)">@Model.YearOfRelease</a></p></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="art-content">
                            <p id="description" name="description">
                                @Model.Description
                            </p>
                            <div class="clear"></div>
                        </div>
                    </article>

                </div>
            </div>

        </div>
    </form>


   